# Generated by Django 4.1.3 on 2022-12-09 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=200)),
                ('house_owner', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('pin_code', models.IntegerField()),
                ('contact_number', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('available_from', models.DateTimeField()),
                ('expected_monthly_rent', models.IntegerField()),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenent.housetype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
